services:
  db:
    image: postgres:latest
    container_name: vdb
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  db: